// Code generated by specs-ci coverage analyze -generate-tests. DO NOT EDIT.
package profiles_test

import (
	"testing"

	"github.com/pablogore/go-specs/specs"
)

func TestGoLibPRStepsForMode_AutoCoverage(t *testing.T) {
	specs.Describe(t, "goLibPRStepsForMode", func(s *specs.Spec) {
		s.It("returns expected value", func(ctx *specs.Context) {
			var result, expected interface{}
			// TODO: call goLibPRStepsForMode and set result and expected
			ctx.Expect(result).ToEqual(expected)
		})
	})
}

func TestExternalPluginConfigFrom_AutoCoverage(t *testing.T) {
	specs.Describe(t, "externalPluginConfigFrom", func(s *specs.Spec) {
		s.It("returns expected value", func(ctx *specs.Context) {
			var result, expected interface{}
			// TODO: call externalPluginConfigFrom and set result and expected
			ctx.Expect(result).ToEqual(expected)
		})
	})
}

func TestRunGoLibRelease_AutoCoverage(t *testing.T) {
	specs.Describe(t, "RunGoLibRelease", func(s *specs.Spec) {
		s.It("returns expected value", func(ctx *specs.Context) {
			var result, expected interface{}
			// TODO: call RunGoLibRelease and set result and expected
			ctx.Expect(result).ToEqual(expected)
		})
	})
}

func TestGoServicePRStepsForMode_AutoCoverage(t *testing.T) {
	specs.Describe(t, "goServicePRStepsForMode", func(s *specs.Spec) {
		s.It("returns expected value", func(ctx *specs.Context) {
			var result, expected interface{}
			// TODO: call goServicePRStepsForMode and set result and expected
			ctx.Expect(result).ToEqual(expected)
		})
	})
}

func TestRunGoServiceRelease_AutoCoverage(t *testing.T) {
	specs.Describe(t, "RunGoServiceRelease", func(s *specs.Spec) {
		s.It("returns expected value", func(ctx *specs.Context) {
			var result, expected interface{}
			// TODO: call RunGoServiceRelease and set result and expected
			ctx.Expect(result).ToEqual(expected)
		})
	})
}

