// Code generated by specs-ci coverage analyze -generate-tests. DO NOT EDIT.
package policy_test

import (
	"testing"

	"github.com/pablogore/go-specs/specs"
)

func TestRuleValues_AutoCoverage(t *testing.T) {
	specs.Describe(t, "ruleValues", func(s *specs.Spec) {
		s.It("returns expected value", func(ctx *specs.Context) {
			var result, expected interface{}
			// TODO: call ruleValues and set result and expected
			ctx.Expect(result).ToEqual(expected)
		})
	})
}

func TestEvaluate_AutoCoverage(t *testing.T) {
	specs.Describe(t, "Evaluate", func(s *specs.Spec) {
		s.It("returns expected value", func(ctx *specs.Context) {
			var result, expected interface{}
			// TODO: call Evaluate and set result and expected
			ctx.Expect(result).ToEqual(expected)
		})
	})
}

func TestLoadPolicies_AutoCoverage(t *testing.T) {
	specs.Describe(t, "LoadPolicies", func(s *specs.Spec) {
		s.It("returns expected value", func(ctx *specs.Context) {
			var result, expected interface{}
			// TODO: call LoadPolicies and set result and expected
			ctx.Expect(result).ToEqual(expected)
		})
	})
}

