// Code generated by specs-ci coverage analyze -generate-tests. DO NOT EDIT.
package guard_test

import (
	"testing"

	"github.com/pablogore/go-specs/specs"
)

func TestValidate_AutoCoverage(t *testing.T) {
	specs.Describe(t, "Validate", func(s *specs.Spec) {
		s.It("returns expected value", func(ctx *specs.Context) {
			var result, expected interface{}
			// TODO: call Validate and set result and expected
			ctx.Expect(result).ToEqual(expected)
		})
	})
}

func TestValidateDomainImports_AutoCoverage(t *testing.T) {
	specs.Describe(t, "validateDomainImports", func(s *specs.Spec) {
		s.It("returns expected value", func(ctx *specs.Context) {
			var result, expected interface{}
			// TODO: call validateDomainImports and set result and expected
			ctx.Expect(result).ToEqual(expected)
		})
	})
}

func TestValidatePortsImports_AutoCoverage(t *testing.T) {
	specs.Describe(t, "validatePortsImports", func(s *specs.Spec) {
		s.It("returns expected value", func(ctx *specs.Context) {
			var result, expected interface{}
			// TODO: call validatePortsImports and set result and expected
			ctx.Expect(result).ToEqual(expected)
		})
	})
}
