package init

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/pablogore/devforge/internal/doctor"
)

const (
	syntegrityDir    = ".syntegrity"
	policiesDir      = ".syntegrity/policies"
	configFileName   = ".syntegrity.yml"
	golangciFileName = ".golangci.yml"
	githubWorkflows  = ".github/workflows"
)

// defaultSyntegrityYAML is the minimal default config written when .syntegrity.yml does not exist.
const defaultSyntegrityYAML = "mode: full\n"

// minimalGolangciYAML is written when .golangci.yml does not exist (optional).
// Production-ready baseline; teams can adjust linters and rules as needed.
const minimalGolangciYAML = `# Generated by DevForge
# Adjust linters according to your team's standards.

version: "2"

run:
  timeout: 5m
  concurrency: 4
  issues-exit-code: 2
  tests: true
  modules-download-mode: readonly
  relative-path-mode: gomod

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - revive
    - gocyclo
    - gosec
    - misspell
    - whitespace

# Optional linters:
#   - errcheck
#   - ineffassign
#   - dupl
#   - prealloc

settings:
  gocyclo:
    min-complexity: 15
  gosec:
    excludes:
      - G115
  misspell:
    locale: US
    ignore-rules:
      - cancelled
      - behaviour

exclusions:
  generated: lax
  presets:
    - comments
    - common-false-positives
    - legacy
    - std-error-handling
  rules:
    - linters:
        - revive
      path: _test.go
      text: context.Context should be the first parameter of a function
    - linters:
        - revive
      path: _test\.go
      text: exported func.*returns unexported type.*which can be annoying to use
    - linters:
        - gosec
      path: _test\.go
      text: Potential hardcoded credentials
  paths:
    - mocks
    - third_party$
    - builtin$
    - examples/.*
    - _test.go$

formatters:
  enable:
    - gofmt
    - goimports
`

// InitResult holds the list of created paths and optional messages (e.g. GitHub workflow suggestion).
//
//nolint:revive // stuttering name is part of the public API
type InitResult struct {
	// Created is the list of file or directory paths created or updated (relative to root).
	Created []string
	// Suggestion is an optional message (e.g. how to add a GitHub workflow).
	Suggestion string
}

// ExistingConfigFiles returns the names of config files that already exist under root
// (.syntegrity.yml, .golangci.yml). Used to warn and prompt before overwriting.
func ExistingConfigFiles(root string) []string {
	var out []string
	for _, name := range []string{configFileName, golangciFileName} {
		if _, err := os.Stat(filepath.Join(root, name)); err == nil {
			out = append(out, name)
		}
	}
	return out
}

// InitRepository bootstraps DevForge configuration at root. It creates .syntegrity/ and
// .syntegrity/policies/, runs doctor.GeneratePolicies to generate policy files, creates
// .syntegrity.yml and .golangci.yml. When force is false, existing config files are not
// overwritten. When force is true, they are overwritten. Returns the list of created/updated
// file paths (relative) and an optional suggestion message (e.g. for adding a GitHub workflow).
//
//nolint:revive // stuttering name is part of the public API
func InitRepository(root string, force bool) (*InitResult, error) {
	var created []string

	policiesPath := filepath.Join(root, policiesDir)
	configPath := filepath.Join(root, configFileName)
	golangciPath := filepath.Join(root, golangciFileName)

	if err := os.MkdirAll(policiesPath, 0750); err != nil {
		return nil, fmt.Errorf("create %s: %w", policiesPath, err)
	}

	generated, err := doctor.GeneratePolicies(root)
	if err != nil {
		return nil, fmt.Errorf("generate policies: %w", err)
	}
	created = append(created, generated...)

	writeConfig := force
	if !writeConfig {
		if _, err := os.Stat(configPath); os.IsNotExist(err) {
			writeConfig = true
		}
	}
	if writeConfig {
		if err := os.WriteFile(configPath, []byte(defaultSyntegrityYAML), 0600); err != nil {
			return nil, fmt.Errorf("write %s: %w", configPath, err)
		}
		created = append(created, configFileName)
	}

	writeGolangci := force
	if !writeGolangci {
		if _, err := os.Stat(golangciPath); os.IsNotExist(err) {
			writeGolangci = true
		}
	}
	if writeGolangci {
		if err := os.WriteFile(golangciPath, []byte(minimalGolangciYAML), 0600); err != nil {
			return nil, fmt.Errorf("write %s: %w", golangciPath, err)
		}
		created = append(created, golangciFileName)
	}

	var suggestion string
	workflowsDir := filepath.Join(root, githubWorkflows)
	if info, err := os.Stat(workflowsDir); err == nil && info.IsDir() {
		if !hasSyntegrityWorkflow(workflowsDir) {
			suggestion = `Add DevForge to your CI pipeline.

Example workflow:

name: CI

on:
  pull_request:

jobs:
  devforge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: devforge/devforge@v1
`
		}
	}

	return &InitResult{Created: created, Suggestion: suggestion}, nil
}

func hasSyntegrityWorkflow(workflowsDir string) bool {
	entries, err := os.ReadDir(workflowsDir)
	if err != nil {
		return false
	}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := strings.ToLower(e.Name())
		if !strings.HasSuffix(name, ".yml") && !strings.HasSuffix(name, ".yaml") {
			continue
		}
		path := filepath.Join(workflowsDir, e.Name())
		//nolint:gosec // G304: path is from ReadDir(workflowsDir), not user input
		data, err := os.ReadFile(path)
		if err != nil {
			continue
		}
		content := string(data)
		if strings.Contains(content, "devforge") || strings.Contains(content, "devforge/devforge") {
			return true
		}
	}
	return false
}
