// Code generated by specs-ci coverage analyze -generate-tests. DO NOT EDIT.
package plugins_test

import (
	"testing"

	"github.com/pablogore/go-specs/specs"
)

func TestDiscover_AutoCoverage(t *testing.T) {
	specs.Describe(t, "Discover", func(s *specs.Spec) {
		s.It("returns expected value", func(ctx *specs.Context) {
			var result, expected interface{}
			// TODO: call Discover and set result and expected
			ctx.Expect(result).ToEqual(expected)
		})
	})
}

