// Code generated by specs-ci coverage analyze -generate-tests. DO NOT EDIT.
package application_test

import (
	"errors"
	"testing"

	"github.com/pablogore/devforge/internal/application"
	"github.com/pablogore/devforge/internal/domain"
	"github.com/pablogore/devforge/internal/steps"
	"github.com/pablogore/devforge/internal/testkit"
	"github.com/pablogore/go-specs/specs"
)

func TestRunWithTitleAndPluginConfig_AutoCoverage(t *testing.T) {
	specs.Describe(t, "RunWithTitleAndPluginConfig", func(s *specs.Spec) {
		s.It("returns expected value", func(ctx *specs.Context) {
			var result, expected interface{}
			// TODO: call RunWithTitleAndPluginConfig and set result and expected
			ctx.Expect(result).ToEqual(expected)
		})
	})
}

func TestRun_AutoCoverage(t *testing.T) {
	specs.Describe(t, "Run", func(s *specs.Spec) {
		s.It("returns expected value", func(ctx *specs.Context) {
			var result, expected interface{}
			// TODO: call Run and set result and expected
			ctx.Expect(result).ToEqual(expected)
		})
	})
}

func TestValidateVersionDerivation_AutoCoverage(t *testing.T) {
	workdir := "/wd"
	pipeline := application.Pipeline{Name: "release", Steps: steps.ReleaseSteps()}

	specs.Describe(t, "ValidateVersionDerivation", func(s *specs.Spec) {
		s.It("valid tag and feat commit returns version", func(ctx *specs.Context) {
			git := &testkit.FakeGitClient{
				GetLatestTagOut:   "v1.0.0",
				GetCommitsSinceOut: []string{"feat: add"},
			}
			u := application.NewReleaseUsecase(nil, git, nil, &testkit.FakeLogger{}, testkit.NewFakeClock().Clock(), pipeline)
			version, err := u.ValidateVersionDerivation(workdir)
			ctx.Expect(err).To(specs.BeNil())
			ctx.Expect(version).ToEqual("v1.1.0")
		})
		s.It("invalid last tag returns ErrInvalidLastTag", func(ctx *specs.Context) {
			git := &testkit.FakeGitClient{
				GetLatestTagOut:   "not-a-version",
				GetCommitsSinceOut: []string{"feat: x"},
			}
			u := application.NewReleaseUsecase(nil, git, nil, &testkit.FakeLogger{}, testkit.NewFakeClock().Clock(), pipeline)
			_, err := u.ValidateVersionDerivation(workdir)
			ctx.Expect(err != nil).To(specs.BeTrue())
			ctx.Expect(errors.Is(err, domain.ErrInvalidLastTag)).To(specs.BeTrue())
		})
		s.It("no releaseable changes returns ErrNoReleaseableChanges", func(ctx *specs.Context) {
			git := &testkit.FakeGitClient{
				GetLatestTagOut:   "v1.0.0",
				GetCommitsSinceOut: []string{"chore: deps"},
			}
			u := application.NewReleaseUsecase(nil, git, nil, &testkit.FakeLogger{}, testkit.NewFakeClock().Clock(), pipeline)
			_, err := u.ValidateVersionDerivation(workdir)
			ctx.Expect(err != nil).To(specs.BeTrue())
			ctx.Expect(errors.Is(err, domain.ErrNoReleaseableChanges)).To(specs.BeTrue())
		})
	})
}

