// Code generated by specs-ci coverage analyze -generate-tests. DO NOT EDIT.
package steps_test

import (
	"context"
	"os"
	"path/filepath"
	"testing"

	"github.com/pablogore/devforge/internal/application"
	"github.com/pablogore/devforge/internal/steps"
	"github.com/pablogore/devforge/internal/testkit"
	"github.com/pablogore/go-specs/specs"
)

func TestInit_AutoCoverage(t *testing.T) {
	specs.Describe(t, "init", func(s *specs.Spec) {
		s.It("returns expected value", func(ctx *specs.Context) {
			var result, expected interface{}
			// TODO: call init and set result and expected
			ctx.Expect(result).ToEqual(expected)
		})
		s.It("IntegrationTestsStep Run succeeds when no build tag", func(ctx *specs.Context) {
			dir := t.TempDir()
			log := &testkit.FakeLogger{}
			appCtx := &application.Context{StdCtx: context.Background(), Workdir: dir, Log: log}
			err := (steps.IntegrationTestsStep{}).Run(appCtx)
			ctx.Expect(err).To(specs.BeNil())
		})
		s.It("IntegrationTestsStep Run returns error when go test fails", func(ctx *specs.Context) {
			dir := t.TempDir()
			ctx.Expect(os.WriteFile(filepath.Join(dir, "x.go"), []byte("//go:build integration\npackage p\n"), 0o600)).To(specs.BeNil())
			cmd := testkit.NewFakeCommandRunner()
			cmd.Stub("go", []string{"test", "-tags=integration", "-count=1", "./..."}, "", os.ErrPermission)
			log := &testkit.FakeLogger{}
			appCtx := &application.Context{StdCtx: context.Background(), Cmd: cmd, Workdir: dir, Log: log}
			err := (steps.IntegrationTestsStep{}).Run(appCtx)
			ctx.Expect(err != nil).To(specs.BeTrue())
		})
	})
}

func TestRun_AutoCoverage(t *testing.T) {
	specs.Describe(t, "Run", func(s *specs.Spec) {
		s.It("success: IntegrationTestsStep Run returns nil when no build tag", func(ctx *specs.Context) {
			dir := t.TempDir()
			log := &testkit.FakeLogger{}
			appCtx := &application.Context{StdCtx: context.Background(), Workdir: dir, Log: log}
			err := (steps.IntegrationTestsStep{}).Run(appCtx)
			ctx.Expect(err).To(specs.BeNil())
		})
		s.It("failure: IntegrationTestsStep Run returns error when go test fails", func(ctx *specs.Context) {
			dir := t.TempDir()
			ctx.Expect(os.WriteFile(filepath.Join(dir, "x.go"), []byte("//go:build integration\npackage p\n"), 0o600)).To(specs.BeNil())
			cmd := testkit.NewFakeCommandRunner()
			cmd.Stub("go", []string{"test", "-tags=integration", "-count=1", "./..."}, "", os.ErrPermission)
			log := &testkit.FakeLogger{}
			appCtx := &application.Context{StdCtx: context.Background(), Cmd: cmd, Workdir: dir, Log: log}
			err := (steps.IntegrationTestsStep{}).Run(appCtx)
			ctx.Expect(err != nil).To(specs.BeTrue())
		})
		s.It("returns expected value", func(ctx *specs.Context) {
			var result, expected interface{}
			// TODO: call Run and set result and expected
			ctx.Expect(result).ToEqual(expected)
		})
	})
}

func TestHasIntegrationBuildTag_AutoCoverage(t *testing.T) {
	specs.Describe(t, "hasIntegrationBuildTag", func(s *specs.Spec) {
		s.It("happy path: empty dir causes IntegrationTestsStep Run to skip and return nil", func(ctx *specs.Context) {
			dir := t.TempDir()
			log := &testkit.FakeLogger{}
			appCtx := &application.Context{StdCtx: context.Background(), Workdir: dir, Log: log}
			err := (steps.IntegrationTestsStep{}).Run(appCtx)
			ctx.Expect(err).To(specs.BeNil())
			ctx.Expect(log.LastInfoMsg).ToEqual("Skipping integration tests (no //go:build integration found)")
		})
		s.It("edge case: dir with //go:build integration causes Run to invoke go test", func(ctx *specs.Context) {
			dir := t.TempDir()
			ctx.Expect(os.WriteFile(filepath.Join(dir, "x.go"), []byte("//go:build integration\npackage p\n"), 0o600)).To(specs.BeNil())
			cmd := testkit.NewFakeCommandRunner()
			cmd.Stub("go", []string{"test", "-tags=integration", "-count=1", "./..."}, "", nil)
			log := &testkit.FakeLogger{}
			appCtx := &application.Context{StdCtx: context.Background(), Cmd: cmd, Workdir: dir, Log: log}
			err := (steps.IntegrationTestsStep{}).Run(appCtx)
			ctx.Expect(err).To(specs.BeNil())
		})
	})
}

func TestDiscoveredPluginSteps_AutoCoverage(t *testing.T) {
	specs.Describe(t, "DiscoveredPluginSteps", func(s *specs.Spec) {
		s.It("returns expected value", func(ctx *specs.Context) {
			var result, expected interface{}
			// TODO: call DiscoveredPluginSteps and set result and expected
			ctx.Expect(result).ToEqual(expected)
		})
	})
}
