// Code generated by specs-ci coverage analyze -generate-tests. DO NOT EDIT.
package domain_test

import (
	"testing"

	"github.com/pablogore/go-specs/specs"
)

func TestValidateConventionalCommit_AutoCoverage(t *testing.T) {
	specs.Describe(t, "ValidateConventionalCommit", func(s *specs.Spec) {
		s.It("returns expected value", func(ctx *specs.Context) {
			var result, expected interface{}
			// TODO: call ValidateConventionalCommit and set result and expected
			ctx.Expect(result).ToEqual(expected)
		})
	})
}

func TestParseCoverage_AutoCoverage(t *testing.T) {
	specs.Describe(t, "ParseCoverage", func(s *specs.Spec) {
		s.It("returns expected value", func(ctx *specs.Context) {
			var result, expected interface{}
			// TODO: call ParseCoverage and set result and expected
			ctx.Expect(result).ToEqual(expected)
		})
	})
}

func TestParseCoverageFromFunc_AutoCoverage(t *testing.T) {
	specs.Describe(t, "ParseCoverageFromFunc", func(s *specs.Spec) {
		s.It("returns expected value", func(ctx *specs.Context) {
			var result, expected interface{}
			// TODO: call ParseCoverageFromFunc and set result and expected
			ctx.Expect(result).ToEqual(expected)
		})
	})
}

func TestExtractSeverity_AutoCoverage(t *testing.T) {
	specs.Describe(t, "extractSeverity", func(s *specs.Spec) {
		s.It("returns expected value", func(ctx *specs.Context) {
			var result, expected interface{}
			// TODO: call extractSeverity and set result and expected
			ctx.Expect(result).ToEqual(expected)
		})
	})
}

