// Code generated by specs-ci coverage analyze -generate-tests. DO NOT EDIT.
package doctor_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/pablogore/devforge/internal/doctor"
	"github.com/pablogore/go-specs/specs"
)

func TestGeneratePolicies_AutoCoverage(t *testing.T) {
	specs.Describe(t, "GeneratePolicies", func(s *specs.Spec) {
		s.It("returns expected value", func(ctx *specs.Context) {
			var result, expected interface{}
			// TODO: call GeneratePolicies and set result and expected
			ctx.Expect(result).ToEqual(expected)
		})
	})
}

func TestWritePolicyFile_AutoCoverage(t *testing.T) {
	specs.Describe(t, "writePolicyFile", func(s *specs.Spec) {
		s.It("happy path: GeneratePolicies with no issues returns nil", func(ctx *specs.Context) {
			root := t.TempDir()
			got, err := doctor.GeneratePolicies(root)
			ctx.Expect(err).To(specs.BeNil())
			ctx.Expect(len(got)).ToEqual(0)
		})
		s.It("error path: cannot create policies dir when .syntegrity is a file", func(ctx *specs.Context) {
			root := t.TempDir()
			ctx.Expect(os.WriteFile(filepath.Join(root, ".syntegrity"), []byte("x"), 0o600)).To(specs.BeNil())
			domainDir := filepath.Join(root, "internal", "domain")
			ctx.Expect(os.MkdirAll(domainDir, 0o750)).To(specs.BeNil())
			ctx.Expect(os.WriteFile(filepath.Join(domainDir, "pkg.go"), []byte("package domain\nimport _ \"internal/adapters\"\n"), 0o600)).To(specs.BeNil())
			_, err := doctor.GeneratePolicies(root)
			ctx.Expect(err != nil).To(specs.BeTrue())
		})
		s.It("edge case: GeneratePolicies with issues writes policies and returns paths", func(ctx *specs.Context) {
			root := t.TempDir()
			domainDir := filepath.Join(root, "internal", "domain")
			ctx.Expect(os.MkdirAll(domainDir, 0o750)).To(specs.BeNil())
			ctx.Expect(os.WriteFile(filepath.Join(domainDir, "pkg.go"), []byte("package domain\nimport _ \"internal/adapters\"\n"), 0o600)).To(specs.BeNil())
			got, err := doctor.GeneratePolicies(root)
			ctx.Expect(err).To(specs.BeNil())
			ctx.Expect(len(got) >= 1).To(specs.BeTrue())
		})
	})
}

func TestPolicyToNode_AutoCoverage(t *testing.T) {
	specs.Describe(t, "policyToNode", func(s *specs.Spec) {
		s.It("returns expected value", func(ctx *specs.Context) {
			var result, expected interface{}
			// TODO: call policyToNode and set result and expected
			ctx.Expect(result).ToEqual(expected)
		})
	})
}

func TestValueToNode_AutoCoverage(t *testing.T) {
	specs.Describe(t, "valueToNode", func(s *specs.Spec) {
		s.It("returns expected value", func(ctx *specs.Context) {
			var result, expected interface{}
			// TODO: call valueToNode and set result and expected
			ctx.Expect(result).ToEqual(expected)
		})
	})
}

func TestDetectDangerousImports_AutoCoverage(t *testing.T) {
	specs.Describe(t, "DetectDangerousImports", func(s *specs.Spec) {
		s.It("returns empty for empty root", func(ctx *specs.Context) {
			root := t.TempDir()
			got := doctor.DetectDangerousImports(root)
			ctx.Expect(len(got)).ToEqual(0)
		})
		s.It("finds pprof import", func(ctx *specs.Context) {
			root := t.TempDir()
			ctx.Expect(os.WriteFile(filepath.Join(root, "main.go"), []byte("package main\nimport _ \"net/http/pprof\"\nfunc main() {}\n"), 0o600)).To(specs.BeNil())
			got := doctor.DetectDangerousImports(root)
			ctx.Expect(len(got)).ToEqual(1)
			ctx.Expect(got[0]).ToEqual("net/http/pprof")
		})
		s.It("skips invalid go file", func(ctx *specs.Context) {
			root := t.TempDir()
			ctx.Expect(os.WriteFile(filepath.Join(root, "broken.go"), []byte("package main\nx\n"), 0o600)).To(specs.BeNil())
			got := doctor.DetectDangerousImports(root)
			ctx.Expect(len(got)).ToEqual(0)
		})
		s.It("skips vendor and dot dirs", func(ctx *specs.Context) {
			root := t.TempDir()
			ctx.Expect(os.MkdirAll(filepath.Join(root, "vendor", "x"), 0o750)).To(specs.BeNil())
			ctx.Expect(os.WriteFile(filepath.Join(root, "vendor", "x", "p.go"), []byte("package x\nimport _ \"net/http/pprof\"\n"), 0o600)).To(specs.BeNil())
			got := doctor.DetectDangerousImports(root)
			ctx.Expect(len(got)).ToEqual(0)
		})
	})
}

func TestDetectAdapterImports_AutoCoverage(t *testing.T) {
	specs.Describe(t, "DetectAdapterImports", func(s *specs.Spec) {
		s.It("returns false when internal/domain missing", func(ctx *specs.Context) {
			root := t.TempDir()
			got := doctor.DetectAdapterImports(root)
			ctx.Expect(got).To(specs.BeFalse())
		})
		s.It("returns true when domain imports adapters", func(ctx *specs.Context) {
			root := t.TempDir()
			domainDir := filepath.Join(root, "internal", "domain")
			ctx.Expect(os.MkdirAll(domainDir, 0o750)).To(specs.BeNil())
			ctx.Expect(os.WriteFile(filepath.Join(domainDir, "pkg.go"), []byte("package domain\nimport _ \"internal/adapters\"\n"), 0o600)).To(specs.BeNil())
			got := doctor.DetectAdapterImports(root)
			ctx.Expect(got).To(specs.BeTrue())
		})
		s.It("skips invalid go file in domain", func(ctx *specs.Context) {
			root := t.TempDir()
			domainDir := filepath.Join(root, "internal", "domain")
			ctx.Expect(os.MkdirAll(domainDir, 0o750)).To(specs.BeNil())
			ctx.Expect(os.WriteFile(filepath.Join(domainDir, "bad.go"), []byte("package domain\nx\n"), 0o600)).To(specs.BeNil())
			got := doctor.DetectAdapterImports(root)
			ctx.Expect(got).To(specs.BeFalse())
		})
	})
}

func TestDetectTimeNowUsage_AutoCoverage(t *testing.T) {
	specs.Describe(t, "DetectTimeNowUsage", func(s *specs.Spec) {
		s.It("returns false when internal/domain missing", func(ctx *specs.Context) {
			root := t.TempDir()
			got := doctor.DetectTimeNowUsage(root)
			ctx.Expect(got).To(specs.BeFalse())
		})
		s.It("returns true when domain has time.Now", func(ctx *specs.Context) {
			root := t.TempDir()
			domainDir := filepath.Join(root, "internal", "domain")
			ctx.Expect(os.MkdirAll(domainDir, 0o750)).To(specs.BeNil())
			ctx.Expect(os.WriteFile(filepath.Join(domainDir, "pkg.go"), []byte("package domain\nimport \"time\"\nfunc f() { _ = time.Now() }\n"), 0o600)).To(specs.BeNil())
			got := doctor.DetectTimeNowUsage(root)
			ctx.Expect(got).To(specs.BeTrue())
		})
		s.It("returns false when domain has no time.Now", func(ctx *specs.Context) {
			root := t.TempDir()
			domainDir := filepath.Join(root, "internal", "domain")
			ctx.Expect(os.MkdirAll(domainDir, 0o750)).To(specs.BeNil())
			ctx.Expect(os.WriteFile(filepath.Join(domainDir, "pkg.go"), []byte("package domain\nfunc f() {}\n"), 0o600)).To(specs.BeNil())
			got := doctor.DetectTimeNowUsage(root)
			ctx.Expect(got).To(specs.BeFalse())
		})
		s.It("skips non-go files", func(ctx *specs.Context) {
			root := t.TempDir()
			domainDir := filepath.Join(root, "internal", "domain")
			ctx.Expect(os.MkdirAll(domainDir, 0o750)).To(specs.BeNil())
			ctx.Expect(os.WriteFile(filepath.Join(domainDir, "readme.txt"), []byte("time.Now()"), 0o600)).To(specs.BeNil())
			got := doctor.DetectTimeNowUsage(root)
			ctx.Expect(got).To(specs.BeFalse())
		})
	})
}

